global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: guestbook-backend
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets:
          - guestbook-alb-oss-1962663365.us-east-1.elb.amazonaws.com
